version: '3.8'

services:

  chat_service:
    build: ./chat_service
    ports:
      - "8000:8000"
    env_file:
      - ./chat_service/.env

  knowledge_base_service:
    build: ./knowledge_base_service
    ports:
      - "8001:8001"

  search_service:
    build: ./search_service
    ports:
      - "8002:8002"

  history_service:
    build: ./history_service
    ports:
      - "8003:8003"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
